### ISSUE TITLE
全局加载组件

### ISSUE THREAD

**Issue by WynnLin** [chikara-chen/react-isomorphic#12]
我想在全局加载一个组件，比如底部导航栏
我把它放在client/common/containers/Common.js里，render里代码如下
`<div>
        <Main>
                    {Children.map(children, child =>
                        cloneElement(child, {...props})
                    )}
         </Main>
         <Foot/>
   </div>`
在dev下显示和操作都是没有问题的，但是build完，npm start运行的时候报错
cannot read property 'shape' of undefined
cannot read property 'call' of undefined
这应该怎么解决呢？

**Comment by chikara-chan** [comment]
没法定位你的问题，描述可以更详细点
