### ISSUE TITLE
client端和server端生成的图片路径不一致

### ISSUE THREAD

**Issue by Undrizzle** [chikara-chen/react-isomorphic#6]
你好，请问为什么client端和server端生成的图片路径不一致？
![as](https://cloud.githubusercontent.com/assets/7947907/23604501/1798f71a-0294-11e7-98a0-0eedde4cfd0a.png)

**Comment by chikara-chan** [comment]
重启服务器还报错吗

**Comment by Undrizzle** [comment]
是的，这个告警一直在，页面上图片是 正常显示的，就是路径相差个“/”

**Comment by chikara-chan** [comment]
插件的bug，传入name参数指定url默认格式解决

**Comment by Undrizzle** [comment]
谢谢
